# Generated by Django 4.1.3 on 2022-11-05 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('c', 'college'), ('s', 'school')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('roll_number', models.IntegerField(unique=True)),
                ('gender', models.CharField(choices=[('u', 'undisclosed'), ('f', 'female'), ('m', 'male')], max_length=1)),
                ('percentage', models.FloatField()),
                ('institue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.institute')),
            ],
        ),
    ]
