# Generated by Django 4.1.3 on 2022-12-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Major_Course',
            new_name='MajorCourse',
        ),
        migrations.RenameModel(
            old_name='Student_Course',
            new_name='StudentCourse',
        ),
    ]
