# Generated by Django 4.1.3 on 2022-11-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='institue',
            new_name='institute',
        ),
        migrations.AlterField(
            model_name='institute',
            name='type',
            field=models.CharField(choices=[('c', 'College'), ('s', 'School')], max_length=1),
        ),
    ]
