# Generated by Django 4.1.3 on 2022-12-04 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_major_course_majorcourse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.major'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='mark',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
