# Generated by Django 4.1.3 on 2022-12-04 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student_major_studentcourse_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.major'),
            preserve_default=False,
        ),
    ]
