# Generated by Django 4.1.3 on 2022-12-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_major'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MajorCourse',
        ),
    ]
